-- JobSwipe consolidated Supabase schema
-- Run this once in the Supabase SQL Editor for a fresh project.

create extension if not exists pgcrypto;

create table if not exists public.students (
    id uuid primary key default gen_random_uuid(),
    student_id text unique not null,
    register_number text unique,
    full_name text not null,
    name text,
    email text unique,
    password_hash text,
    gender text,
    department text not null default 'CSE',
    branch text,
    college_name text,
    "10th_marks" double precision,
    "10th_board" text,
    "12th_marks" double precision,
    "12th_board" text,
    cgpa double precision default 0,
    backlogs_history integer default 0,
    active_backlogs integer default 0,
    year_of_study integer,
    batch_year integer,
    skills text[] default '{}',
    certifications text[] default '{}',
    projects text[] default '{}',
    resume_url text,
    resume_parse_confidence jsonb default '{}'::jsonb,
    portfolio_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.recruiters (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    company_name text not null,
    company_domain text not null,
    email text unique not null,
    password_hash text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.companies (
    company_id text primary key,
    company_name text not null,
    industry text,
    tier text,
    min_cgpa double precision,
    min_10th double precision,
    min_12th double precision,
    max_active_backlogs integer default 0,
    allowed_departments text,
    required_skills text,
    preferred_skills text,
    min_internship_months double precision default 0,
    internship_tier_preference text default 'Any',
    min_projects integer default 0,
    project_complexity_min text default 'Basic',
    requires_research_paper boolean default false,
    cert_tier_required text default 'None',
    role_offered text,
    package_lpa double precision,
    bond_years integer default 0
);

create table if not exists public.jobs (
    id uuid primary key default gen_random_uuid(),
    recruiter_id uuid references public.recruiters(id) on delete set null,
    company_name text,
    role text,
    role_title text,
    industry text,
    location text,
    remote_policy text check (remote_policy in ('on-site', 'hybrid', 'remote')),
    allowed_branches text[] default '{}',
    allowed_departments text[] default '{}',
    min_cgpa double precision default 0,
    max_backlogs integer default 0,
    batch_year integer,
    grad_years_eligible integer[] default '{}',
    required_skills text[] default '{}',
    preferred_skills text[] default '{}',
    ctc text,
    package_lpa double precision,
    bond_years integer default 0,
    selection_rounds text[] default '{}',
    interview_timeline text,
    mentorship text,
    highlight_line text,
    job_description text,
    careers_url text,
    is_active boolean default true,
    created_at timestamptz not null default now()
);

create table if not exists public.certifications (
    cert_id text primary key,
    student_id text references public.students(student_id) on delete cascade,
    cert_name text not null,
    issuing_body text,
    tier text,
    domain text,
    year_obtained integer
);

create table if not exists public.projects (
    project_id text primary key,
    student_id text references public.students(student_id) on delete cascade,
    project_title text,
    domain text,
    tech_stack text,
    complexity text,
    team_size text,
    has_deployment boolean default false,
    has_github boolean default false,
    duration_weeks integer,
    year integer
);

create table if not exists public.internships (
    internship_id text primary key,
    student_id text references public.students(student_id) on delete cascade,
    company_name text,
    company_tier text,
    role text,
    domain text,
    duration_months double precision,
    stipend boolean default false,
    mode text,
    year integer
);

create table if not exists public.research_papers (
    paper_id text primary key,
    student_id text references public.students(student_id) on delete cascade,
    title text,
    publication_venue text,
    tier text,
    domain text,
    year_published integer,
    is_first_author boolean default false,
    co_authors_count integer default 0
);

create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    student_id text references public.students(student_id) on delete cascade,
    skill_name text not null,
    proficiency text,
    verified boolean default false
);

create table if not exists public.applications (
    id uuid primary key default gen_random_uuid(),
    student_id text not null references public.students(student_id) on delete cascade,
    job_id uuid not null references public.jobs(id) on delete cascade,
    current_status text not null default 'Applied',
    round_results jsonb default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (student_id, job_id)
);

create table if not exists public.skills_graph (
    id bigint generated by default as identity primary key,
    skill_name text unique not null,
    category text,
    related_skills text[] default '{}',
    difficulty_level text,
    avg_learning_weeks integer,
    industry_demand_score double precision
);

create table if not exists public.learning_resources (
    id bigint generated by default as identity primary key,
    skill_name text not null,
    resource_type text,
    title text,
    platform text,
    link text,
    difficulty text,
    duration_hours integer,
    is_free boolean default true
);

create table if not exists public.upskilling_plans (
    id uuid primary key default gen_random_uuid(),
    student_id text not null references public.students(student_id) on delete cascade,
    job_id uuid references public.jobs(id) on delete cascade,
    plan jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.eligibility_results (
    id bigint generated by default as identity primary key,
    student_id text references public.students(student_id) on delete cascade,
    company_id text references public.companies(company_id) on delete cascade,
    eligible boolean not null,
    score double precision,
    criteria_breakdown jsonb,
    timestamp timestamptz default now(),
    unique (student_id, company_id)
);

create table if not exists public.improvement_plans (
    id bigint generated by default as identity primary key,
    student_id text references public.students(student_id) on delete cascade,
    company_id text references public.companies(company_id) on delete cascade,
    suggestions jsonb,
    timestamp timestamptz default now(),
    unique (student_id, company_id)
);

create table if not exists public.bias_recommendations (
    id bigint generated by default as identity primary key,
    company_id text not null references public.companies(company_id) on delete cascade,
    criterion text not null,
    current_threshold text,
    recommended_threshold text,
    current_disparity double precision,
    projected_disparity double precision,
    current_pool_size integer,
    projected_pool_size integer,
    recommendation_type text not null default 'threshold' check (recommendation_type in ('threshold', 'substitution')),
    simulation_payload jsonb,
    created_at timestamptz not null default now(),
    status text not null default 'proposed' check (status in ('proposed', 'accepted', 'rejected', 'implemented'))
);

create table if not exists public.model_fairness_history (
    id bigint generated by default as identity primary key,
    company_id text not null references public.companies(company_id) on delete cascade,
    epsilon double precision not null,
    accuracy double precision,
    f1 double precision,
    delta_dp double precision,
    delta_eo double precision,
    trained_at timestamptz not null default now(),
    triggered_by text not null
);

create table if not exists public.student_interest (
    id uuid primary key default gen_random_uuid(),
    student_id text not null references public.students(student_id) on delete cascade,
    job_id uuid references public.jobs(id) on delete cascade,
    created_at timestamptz default now(),
    unique (student_id, job_id)
);

create table if not exists public.recruiter_interest (
    id uuid primary key default gen_random_uuid(),
    recruiter_id uuid references public.recruiters(id) on delete cascade,
    student_id text not null references public.students(student_id) on delete cascade,
    job_id uuid references public.jobs(id) on delete cascade,
    created_at timestamptz default now(),
    unique (recruiter_id, student_id, job_id)
);

create table if not exists public.matches (
    id uuid primary key default gen_random_uuid(),
    student_id text not null references public.students(student_id) on delete cascade,
    recruiter_id uuid references public.recruiters(id) on delete cascade,
    job_id uuid references public.jobs(id) on delete cascade,
    matched_at timestamptz default now(),
    unique (student_id, job_id)
);

create table if not exists public.student_pass (
    id uuid primary key default gen_random_uuid(),
    student_id text not null references public.students(student_id) on delete cascade,
    job_id uuid references public.jobs(id) on delete cascade,
    created_at timestamptz default now(),
    unique (student_id, job_id)
);

create table if not exists public.recruiter_pass (
    id uuid primary key default gen_random_uuid(),
    recruiter_id uuid references public.recruiters(id) on delete cascade,
    student_id text not null references public.students(student_id) on delete cascade,
    created_at timestamptz default now(),
    unique (recruiter_id, student_id)
);

create index if not exists idx_students_student_id on public.students(student_id);
create index if not exists idx_students_register_number on public.students(register_number);
create index if not exists idx_jobs_recruiter on public.jobs(recruiter_id);
create index if not exists idx_jobs_active on public.jobs(is_active);
create index if not exists idx_certs_student on public.certifications(student_id);
create index if not exists idx_projects_student on public.projects(student_id);
create index if not exists idx_internships_student on public.internships(student_id);
create index if not exists idx_papers_student on public.research_papers(student_id);
create index if not exists idx_skills_student on public.skills(student_id);
create index if not exists idx_applications_student on public.applications(student_id);
create index if not exists idx_eligibility_student on public.eligibility_results(student_id);
create index if not exists idx_eligibility_company on public.eligibility_results(company_id);
create index if not exists idx_improvement_student on public.improvement_plans(student_id);
create index if not exists idx_bias_recommendations_company on public.bias_recommendations(company_id);
create index if not exists idx_bias_recommendations_created_at on public.bias_recommendations(created_at desc);
create index if not exists idx_fairness_history_company on public.model_fairness_history(company_id);
create index if not exists idx_fairness_history_trained_at on public.model_fairness_history(trained_at desc);
create index if not exists idx_student_interest_student on public.student_interest(student_id);
create index if not exists idx_recruiter_interest_recruiter on public.recruiter_interest(recruiter_id);
create index if not exists idx_matches_student on public.matches(student_id);
create index if not exists idx_matches_recruiter on public.matches(recruiter_id);

alter table public.students enable row level security;
alter table public.recruiters enable row level security;
alter table public.companies enable row level security;
alter table public.jobs enable row level security;
alter table public.certifications enable row level security;
alter table public.projects enable row level security;
alter table public.internships enable row level security;
alter table public.research_papers enable row level security;
alter table public.skills enable row level security;
alter table public.applications enable row level security;
alter table public.skills_graph enable row level security;
alter table public.learning_resources enable row level security;
alter table public.upskilling_plans enable row level security;
alter table public.eligibility_results enable row level security;
alter table public.improvement_plans enable row level security;
alter table public.bias_recommendations enable row level security;
alter table public.model_fairness_history enable row level security;
alter table public.student_interest enable row level security;
alter table public.recruiter_interest enable row level security;
alter table public.matches enable row level security;
alter table public.student_pass enable row level security;
alter table public.recruiter_pass enable row level security;

drop policy if exists "Allow all reads on students" on public.students;
create policy "Allow all reads on students" on public.students for select using (true);
drop policy if exists "Allow all reads on recruiters" on public.recruiters;
create policy "Allow all reads on recruiters" on public.recruiters for select using (true);
drop policy if exists "Allow all reads on companies" on public.companies;
create policy "Allow all reads on companies" on public.companies for select using (true);
drop policy if exists "Allow all reads on jobs" on public.jobs;
create policy "Allow all reads on jobs" on public.jobs for select using (true);
drop policy if exists "Allow all reads on certifications" on public.certifications;
create policy "Allow all reads on certifications" on public.certifications for select using (true);
drop policy if exists "Allow all reads on projects" on public.projects;
create policy "Allow all reads on projects" on public.projects for select using (true);
drop policy if exists "Allow all reads on internships" on public.internships;
create policy "Allow all reads on internships" on public.internships for select using (true);
drop policy if exists "Allow all reads on research_papers" on public.research_papers;
create policy "Allow all reads on research_papers" on public.research_papers for select using (true);
drop policy if exists "Allow all reads on skills" on public.skills;
create policy "Allow all reads on skills" on public.skills for select using (true);
drop policy if exists "Allow all reads on applications" on public.applications;
create policy "Allow all reads on applications" on public.applications for select using (true);
drop policy if exists "Allow all reads on skills_graph" on public.skills_graph;
create policy "Allow all reads on skills_graph" on public.skills_graph for select using (true);
drop policy if exists "Allow all reads on learning_resources" on public.learning_resources;
create policy "Allow all reads on learning_resources" on public.learning_resources for select using (true);
drop policy if exists "Allow all reads on upskilling_plans" on public.upskilling_plans;
create policy "Allow all reads on upskilling_plans" on public.upskilling_plans for select using (true);
drop policy if exists "Allow all reads on eligibility_results" on public.eligibility_results;
create policy "Allow all reads on eligibility_results" on public.eligibility_results for select using (true);
drop policy if exists "Allow all reads on improvement_plans" on public.improvement_plans;
create policy "Allow all reads on improvement_plans" on public.improvement_plans for select using (true);
drop policy if exists "Allow all reads on bias_recommendations" on public.bias_recommendations;
create policy "Allow all reads on bias_recommendations" on public.bias_recommendations for select using (true);
drop policy if exists "Allow all writes on bias_recommendations" on public.bias_recommendations;
create policy "Allow all writes on bias_recommendations" on public.bias_recommendations for insert with check (true);
drop policy if exists "Allow all reads on model_fairness_history" on public.model_fairness_history;
create policy "Allow all reads on model_fairness_history" on public.model_fairness_history for select using (true);
drop policy if exists "Allow all writes on model_fairness_history" on public.model_fairness_history;
create policy "Allow all writes on model_fairness_history" on public.model_fairness_history for insert with check (true);
drop policy if exists "Allow all reads on student_interest" on public.student_interest;
create policy "Allow all reads on student_interest" on public.student_interest for select using (true);
drop policy if exists "Allow all reads on recruiter_interest" on public.recruiter_interest;
create policy "Allow all reads on recruiter_interest" on public.recruiter_interest for select using (true);
drop policy if exists "Allow all reads on matches" on public.matches;
create policy "Allow all reads on matches" on public.matches for select using (true);
drop policy if exists "Allow all reads on student_pass" on public.student_pass;
create policy "Allow all reads on student_pass" on public.student_pass for select using (true);
drop policy if exists "Allow all reads on recruiter_pass" on public.recruiter_pass;
create policy "Allow all reads on recruiter_pass" on public.recruiter_pass for select using (true);
