create table if not exists public.bias_recommendations (
    id bigint generated by default as identity primary key,
    company_id text not null references public.companies(company_id) on delete cascade,
    criterion text not null,
    current_threshold text,
    recommended_threshold text,
    current_disparity double precision,
    projected_disparity double precision,
    current_pool_size integer,
    projected_pool_size integer,
    recommendation_type text not null default 'threshold' check (recommendation_type in ('threshold', 'substitution')),
    simulation_payload jsonb,
    created_at timestamptz not null default now(),
    status text not null default 'proposed' check (status in ('proposed', 'accepted', 'rejected', 'implemented'))
);

create index if not exists idx_bias_recommendations_company on public.bias_recommendations(company_id);
create index if not exists idx_bias_recommendations_created_at on public.bias_recommendations(created_at desc);

create table if not exists public.model_fairness_history (
    id bigint generated by default as identity primary key,
    company_id text not null references public.companies(company_id) on delete cascade,
    epsilon double precision not null,
    accuracy double precision,
    f1 double precision,
    delta_dp double precision,
    delta_eo double precision,
    trained_at timestamptz not null default now(),
    triggered_by text not null
);

create index if not exists idx_model_fairness_history_company on public.model_fairness_history(company_id);
create index if not exists idx_model_fairness_history_trained_at on public.model_fairness_history(trained_at desc);

alter table public.bias_recommendations enable row level security;
alter table public.model_fairness_history enable row level security;

drop policy if exists "Allow bias recommendation reads" on public.bias_recommendations;
create policy "Allow bias recommendation reads"
on public.bias_recommendations for select
using (true);

drop policy if exists "Allow bias recommendation writes" on public.bias_recommendations;
create policy "Allow bias recommendation writes"
on public.bias_recommendations for insert
with check (true);

drop policy if exists "Allow fairness history reads" on public.model_fairness_history;
create policy "Allow fairness history reads"
on public.model_fairness_history for select
using (true);

drop policy if exists "Allow fairness history writes" on public.model_fairness_history;
create policy "Allow fairness history writes"
on public.model_fairness_history for insert
with check (true);
